name: Backup ğŸ“€

on:
  schedule:
    - cron: 0 4 * * *
  push:
    branches: [main]

jobs:
  backup:
    name: Back me up ğŸ‘Š
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code ğŸšš
        uses: actions/checkout@v3
      - name: Install SSH Key ğŸ”‘
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts ğŸ’¾
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Restart server ğŸ
        run: scp ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/wishlist.ru-coding.nl/database/production.db ./
      - name: Upload as artifact ğŸ“Ÿ
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./production.db
